# Generated by Django 5.2.7 on 2025-10-18 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('prompt', models.TextField(blank=True, verbose_name='Базовый промт')),
                ('slides_count', models.PositiveIntegerField(default=0, verbose_name='Количество слайдов')),
                ('images_count', models.PositiveIntegerField(default=0, verbose_name='Количество изображений')),
            ],
            options={
                'verbose_name': 'Шаблон презентации',
                'verbose_name_plural': 'Шаблоны презентаций',
            },
        ),
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='template_images/', verbose_name='Изображение')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='presentations.presentationtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='UserPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название презентации')),
                ('user_prompt', models.TextField(blank=True, verbose_name='Промт пользователя')),
                ('full_prompt', models.TextField(blank=True, verbose_name='Склеенный промт')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='JSON со слайдами')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_presentations', to='presentations.presentationtemplate', verbose_name='Шаблон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_presentations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Презентация пользователя',
                'verbose_name_plural': 'Презентации пользователей',
            },
        ),
    ]
