# Generated by Django 5.2.7 on 2025-11-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationtemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание шаблона'),
        ),
    ]
