# Generated by Django 5.2.7 on 2025-11-18 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_presentationtemplate_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpresentation',
            options={},
        ),
        migrations.AddField(
            model_name='presentationtemplate',
            name='pptx_file',
            field=models.FileField(blank=True, null=True, upload_to='template_pptx/', verbose_name='PPTX шаблон'),
        ),
        migrations.AddField(
            model_name='userpresentation',
            name='pptx_file',
            field=models.FileField(blank=True, null=True, upload_to='user_presentations/', verbose_name='PPTX презентация'),
        ),
        migrations.AlterField(
            model_name='userpresentation',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userpresentation',
            name='full_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userpresentation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_presentations', to='presentations.presentationtemplate'),
        ),
        migrations.AlterField(
            model_name='userpresentation',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userpresentation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_presentations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpresentation',
            name='user_prompt',
            field=models.TextField(blank=True),
        ),
    ]
