# Generated by Django 5.2.7 on 2025-11-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_alter_userpresentation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpresentation',
            name='image_prompt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
